# .github/workflows/test-coverage.yaml

# Run on pushes to main and on pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Test coverage

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::DT, any::htmltools, any::xml2, any::visNetwork, any::igraph, any::jsonlite, any::processx, any::dplyr, any::ggdag, any::knitr, any::reticulate, any::rix, any::rmarkdown, any::testthat, any::usethis

      - name: Run covr, generate reports & display coverage.txt
        shell: bash
        run: |
          # run coverage
          Rscript -e "
            cov <- covr::package_coverage()
            df <- as.data.frame(cov)
            writeLines(capture.output(print(df)), 'coverage.txt')
            covr::report(cov, file = 'coverage.html', browse = FALSE)
          "

          # show coverage.txt in CI logs
          echo "## Coverage text report:";
          sed 's/^/    /' coverage.txt;

          # append full HTML report to GitHub Actions summary
          echo "## HTML coverage report" >> $GITHUB_STEP_SUMMARY
          # indent HTML so summary renders correctly
          sed 's/^/    /' coverage.html >> $GITHUB_STEP_SUMMARY

