# .github/workflows/test-coverage.yaml

# Run on pushes to main and on pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Test coverage

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::tinytable, any::covr, any::DT, any::htmltools, any::xml2, any::visNetwork, any::igraph, any::jsonlite, any::processx, any::dplyr, any::ggdag, any::knitr, any::reticulate, any::rix, any::rmarkdown, any::testthat, any::usethis

      - name: Run covr, capture coverage and display
        shell: bash
        run: |
          # run coverage and sink full output to file
          Rscript -e "
            cov <- covr::package_coverage()
            tinytable::save_tt(tinytable::tt(cov), output = 'coverage.md')
            cov
          "

          # append full coverage text into GitHub Actions summary
          cat coverage.md >> $GITHUB_STEP_SUMMARY
