# .github/workflows/test-coverage.yaml

# Run on pushes to main and on pull requests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Test coverage

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::tinytable, any::covr, any::DT, any::htmltools, any::xml2, any::visNetwork, any::igraph, any::jsonlite, any::processx, any::dplyr, any::ggdag, any::knitr, any::reticulate, any::rix, any::rmarkdown, any::testthat, any::usethis

      - name: Run covr, capture coverage and display
        shell: bash
        run: |
          # run coverage and sink full output to file
          Rscript -e "
            cov <- covr::package_coverage()
            cov_list <- covr::coverage_to_list(cov)
            cov_df <- as.data.frame(cov_list['filecoverage'])
            total_cov <- cov_list['totalcoverage']
            tinytable::save_tt(tinytable::tt(cov_df), output = 'coverage.md')
            # append total coverage at end of markdown
            cat(sprintf('\n\n\nTotal coverage: %s', total_cov), file = 'coverage.md', append = TRUE)
            cov
          "

          # convert to GitHub-Flavored Markdown table:
          # drop all lines beginning with '+'
          grep -v '^+' coverage.md > coverage.tmp
          # insert GFM header separator after first line
          { head -n1 coverage.tmp; echo '|--------------|---------------|'; tail -n +2 coverage.tmp; } > coverage.md
          rm coverage.tmp

          # append full coverage text into GitHub Actions summary
          cat coverage.md >> $GITHUB_STEP_SUMMARY
