name: Trigger Demo Actions

on:
  push:
    branches:
      - [main, master]

jobs:
  trigger-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event to rixpress_demos
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.TRIGGER_DEMOS }}" \
            https://api.github.com/repos/b-rodrigues/rixpress_demos/dispatches \
            -d '{"event_type": "trigger-demo", "client_payload": {"ref": "${GITHUB_REF}"}}'
