# Integration tests for making pipeline
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-rixpress-simple-pipeline

permissions:
  contents: write

jobs:
  devtools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Create this folder to silence warning
        run: mkdir -p ~/.nix-defexpr/channels

      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Generate pipeline.nix
        run: |
          nix-shell --run "cd data-raw && Rscript -e \"devtools::load_all();source('gen_pipeline.R')\""

      - name: Check generated default.nix
        run: cat data-raw/pipeline.nix

      - name: Convert dag to ASCII art
        run: |
          nix-shell -p graphviz -p --run "cd data-raw && dot -Tpng dag.dot -o dag.png"
          echo '```' >> $GITHUB_STEP_SUMMARY
          nix-shell -p chafa --ran "chafa --symbols braille --no-colors data-raw/dag.png >> $GITHUB_STEP_SUMMARY"
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Make pipeline
        run: |
          nix-shell --run "cd data-raw && Rscript -e \"devtools::load_all();rixpress::rxp_make()\""
