# Integration tests for making pipeline
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-rixpress-simple-pipeline

permissions:
  contents: write

jobs:
  devtools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix

      - name: Build default.nix with 2 packages
        run: |
          nix-shell --run "cd data-raw && Rscript -e \"devtools::load_all();source('gen_pipeline.R')\""

      - name: Check generated default.nix
        run: cat data-raw/pipeline.nix

      - name: Convert dag
        run: |
          nix-shell -p graphviz --run "cd data-raw && dot -Tpng dag.dot -o dag.png"

      - name: View Dag
        run: |
          nix-shell -p catimg --run "cd data-raw && catimg dag.png"

      - name: Make pipeline
        run: |
          nix-shell --run "cd data-raw && Rscript -e \"devtools::load_all();rixpress::rxp_make()\""
